version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: shopsmart-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: shopsmart-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/shopsmart
    depends_on:
      - mongodb

  client:
    build: ./client
    container_name: shopsmart-frontend
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongo-data:
