name: CI

on:
  workflow_dispatch:

jobs:
  client:
    name: Client CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run tests (Unit)
        run: npm test -- --run --reporter=default --reporter=junit --outputFile=junit.xml
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: client-test-report
          path: client/junit.xml
      - name: Test Report Annotation
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Client Tests
          path: client/junit.xml
          reporter: java-junit

      - name: Build
        run: npm run build

  server:
    name: Server CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test -- --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_DIR: ./
          JEST_JUNIT_OUTPUT_NAME: junit.xml
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: server-test-report
          path: server/junit.xml
      - name: Test Report Annotation
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Server Tests
          path: server/junit.xml
          reporter: jest-junit
