name: Docker Deploy

on:
  push:
    branches: [ "docker" ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker build ./server -t ${{secrets.DOCKERHUB_USERNAME}}/shopsmart-backend
    - run: docker build ./client -t ${{secrets.DOCKERHUB_USERNAME}}/shopsmart-frontend
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push ${{secrets.DOCKERHUB_USERNAME}}/shopsmart-backend:latest
    - run: docker push ${{secrets.DOCKERHUB_USERNAME}}/shopsmart-frontend:latest